apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlepedidos
  namespace: controle-pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlepedidos
  template:
    metadata:
      labels:
        app: controlepedidos
    spec:
      containers:
        - name: controlepedidos
          image: webertonfaria/controlepedidos:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/controle_pedidos
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: controlepedidos
  namespace: controle-pedidos
spec:
  type: NodePort
  selector:
    app: controlepedidos
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # optional fixed port for testing
